---
title: "Report word"
format: docx
---

# Import and clean data

```{r}
#| file: ../throughput/import_clean.R
#| warning: false
#| echo: false
```

# Descriptives

```{r}
#| file: ../throughput/descriptives.R
#| warning: false
#| echo: false
```

```{r}
tbl_descriptive
```

# Graphs

```{r}
#| file: ../throughput/graphs.R
#| warning: false
#| message: false
#| echo: false
```

<!-- We keep the ratio of each graph so that is the same for all of them -->
<!-- the height of each graph will be arbitrarily 4 -->
<!-- 4 rows: 4x4 = height 16 -->

```{r}
#| label: fig-sociod
#| fig-cap: Sociodemographics
#| fig-width: 12
#| fig-height: 16

plots_sociod
```

<!-- 3 rows: 4x3 = height 12 -->

```{r}
#| label: fig-social
#| fig-cap: Social aspects
#| fig-width: 12
#| fig-height: 12
#| warning: false

plots_social
```

<!-- 5 rows: 4x5 = height 20 -->

```{r}
#| label: fig-health
#| fig-cap: Health and wellbeing
#| fig-width: 12
#| fig-height: 20
#| warning: false

plots_health
```

# Multivariate

```{r}
#| file: ../throughput/multivariate.R
#| warning: false
#| echo: false
```

## Univariate

```{r}
# tbl_univ
```


## Multivariate table + foresplot

```{r}
#| fig-format: retina
#| fig-dpi: 300
#| fig-width: 10
#| fig-height: 12
forest_table_plot
```
