---
title: "Results"
description: ""
date: today
author: 
 - name: "Jesus Sierralaya"
   url: https://github.com/JesusSierralaya
   affiliation: CCOMS-UAM
   affiliation-url: https://github.com/CCOMS-UAM
title-block-banner: true
format:
  html:
    theme: flatly
    code-fold: true
    code-tools: true
    # code-link: true
    toc: true
    number-sections: true
    # # df-print: paged
    self-contained: true
---

```{r setup}
#| include: false
# knitr::opts_chunk$set(fig.width=12, fig.height=10) 
```

# Reliability

```{r}
#| file: ../throughput/reliability.R
#| warning: false
```
# Import and clean data

```{r}
#| file: ../throughput/import_clean.R
#| warning: false
```

## db_longer_NA

```{r}
look_for(db_longer_NA, details = "full")
```

## db_longer

```{r}
look_for(db_longer, details = "full")
```

## db_pre_post

```{r}
look_for(db_pre_post, details = "full")
```

# Descriptives

## Table descriptives

```{r}
#| file: ../throughput/descriptives.R
#| warning: false
```

## Graphs 

```{r}
#| file: ../throughput/graphs.R
#| warning: false
```

### Socidemographics

```{r}
#| label: fig-sociod 
#| fig-cap: Sociodemographics
#| fig-width: 12
#| fig-height: 10

plot_sociod 
```

### Social Aspects

```{r}
#| label: fig-social 
#| fig-cap: Social aspects
#| fig-width: 12
#| fig-height: 10
#| warning: false

plot_social 
```

### Health and wellbeing

```{r}
#| label: fig-health
#| fig-cap: Health and wellbeing
#| fig-width: 12
#| fig-height: 12
#| warning: false

plot_health 
```

# Univariate

```{r}
#| file: ../throughput/multivariate.R
tbl_univ
```

# Multivariate

```{r}
tbl_multi
```

## Plot Multivariate

```{r}
#| fig-height: 10
plot_multi
```