---
title: "Results"
description: ""
date: today
author: 
 - name: "Jesus Sierralaya"
   url: https://github.com/JesusSierralaya
   affiliation: CCOMS-UAM
   affiliation-url: https://github.com/CCOMS-UAM
title-block-banner: true
format:
  html:
    theme: flatly
    code-fold: true
    code-tools: true
    # code-link: true
    toc: true
    number-sections: true
    # # df-print: paged
    self-contained: true
---

```{r setup}
#| include: false
# knitr::opts_chunk$set(fig.width=12, fig.height=10) 
```

# Import and clean data

```{r}
#| file: ../throughput/import_clean_2.R
#| warning: false
```

# Descriptives

```{r}
#| file: ../throughput/descriptives_2.R
#| warning: false
```

```{r}
tbl_descriptive
```

# Graphs

```{r}
#| file: ../throughput/graphs_2.R
#| warning: false
#| include: false
```

```{r}
#| label: fig-sociod
#| fig-cap: Sociodemographics
#| fig-width: 10
#| fig-height: 20

plots_sociod
```

```{r}
#| label: fig-social
#| fig-cap: Social aspects
#| fig-width: 10
#| fig-height: 15
#| warning: false

plots_social
```

```{r}
#| label: fig-health
#| fig-cap: Health and wellbeing
#| fig-width: 12
#| fig-height: 20
#| warning: false

plots_health
```

# Multivariate

```{r}
#| file: ../throughput/multivariate_2.R
#| warning: false
```

## Univariate

```{r}
tbl_univ
```


## Multivariate table

```{r}
tbl_multi
```

## Multivariate Plot

```{r}
#| fig-height: 10
plot_multi
```